[package]
name = "sortinator"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
chrono = { version = "0.4.41", features = ["serde"] }
clap = { version = "4.5.37", features = ["derive"] }
serde = { version = "1.0.219", features = ["serde_derive"] }
serde_yml = "0.0.12"
